# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
development:
  adapter: postgresql
  encoding: utf8
  port: 3306
  database: lentil
  pool: 5
  username: postgres
production:
  adapter: postgresql
  encoding: utf8
  port: 3306
  database: lentil
  pool: 5
  username: postgres
